package tm.server.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import tm.common.api.webservice.TaskService;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T15:21:20.933+03:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "TaskWebServiceBeanService",
                  wsdlLocation = "http://localhost:8080/taskService/?wsdl",
                  targetNamespace = "http://webservice.server.tm/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00", comments = "Apache CXF 3.3.2")
public class TaskWebServiceBeanService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public final static QName SERVICE = new QName("http://webservice.server.tm/", "TaskWebServiceBeanService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public final static QName TaskWebServiceBeanPort = new QName("http://webservice.server.tm/", "TaskWebServiceBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/taskService/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaskWebServiceBeanService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/taskService/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskWebServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskWebServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskWebServiceBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskWebServiceBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskWebServiceBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskWebServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TaskService
     */
    @WebEndpoint(name = "TaskWebServiceBeanPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskService getTaskWebServiceBeanPort() {
        return super.getPort(TaskWebServiceBeanPort, TaskService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskService
     */
    @WebEndpoint(name = "TaskWebServiceBeanPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:20.933+03:00")
    public TaskService getTaskWebServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(TaskWebServiceBeanPort, TaskService.class, features);
    }

}
