package tm.common.api.webservice;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-06T09:58:33.636+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://webservice.api.common.tm/", name = "serverService")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00", comments = "Apache CXF 3.3.2")
public interface ServerService {

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataLoadFasterXmlRequest", output = "http://webservice.api.common.tm/serverService/dataLoadFasterXmlResponse")
    @RequestWrapper(localName = "dataLoadFasterXml", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadFasterXml")
    @ResponseWrapper(localName = "dataLoadFasterXmlResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadFasterXmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataLoadFasterXml(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataSaveFasterJsonRequest", output = "http://webservice.api.common.tm/serverService/dataSaveFasterJsonResponse")
    @RequestWrapper(localName = "dataSaveFasterJson", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveFasterJson")
    @ResponseWrapper(localName = "dataSaveFasterJsonResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveFasterJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataSaveFasterJson(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/shutdownRequest", output = "http://webservice.api.common.tm/serverService/shutdownResponse")
    @RequestWrapper(localName = "shutdown", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.Shutdown")
    @ResponseWrapper(localName = "shutdownResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ShutdownResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean shutdown(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataClearFasterJsonRequest", output = "http://webservice.api.common.tm/serverService/dataClearFasterJsonResponse")
    @RequestWrapper(localName = "dataClearFasterJson", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearFasterJson")
    @ResponseWrapper(localName = "dataClearFasterJsonResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearFasterJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataClearFasterJson(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataClearBinaryRequest", output = "http://webservice.api.common.tm/serverService/dataClearBinaryResponse")
    @RequestWrapper(localName = "dataClearBinary", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearBinary")
    @ResponseWrapper(localName = "dataClearBinaryResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearBinaryResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataClearBinary(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/setSortMethodRequest", output = "http://webservice.api.common.tm/serverService/setSortMethodResponse")
    @RequestWrapper(localName = "setSortMethod", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.SetSortMethod")
    @ResponseWrapper(localName = "setSortMethodResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.SetSortMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean setSortMethod(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        tm.common.api.webservice.ComparatorType arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/showHelpRequest", output = "http://webservice.api.common.tm/serverService/showHelpResponse")
    @RequestWrapper(localName = "showHelp", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ShowHelp")
    @ResponseWrapper(localName = "showHelpResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ShowHelpResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.String showHelp(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataClearJaxbJsonRequest", output = "http://webservice.api.common.tm/serverService/dataClearJaxbJsonResponse")
    @RequestWrapper(localName = "dataClearJaxbJson", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearJaxbJson")
    @ResponseWrapper(localName = "dataClearJaxbJsonResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearJaxbJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataClearJaxbJson(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataLoadBinaryRequest", output = "http://webservice.api.common.tm/serverService/dataLoadBinaryResponse")
    @RequestWrapper(localName = "dataLoadBinary", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadBinary")
    @ResponseWrapper(localName = "dataLoadBinaryResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadBinaryResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataLoadBinary(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataClearJaxbXmlRequest", output = "http://webservice.api.common.tm/serverService/dataClearJaxbXmlResponse")
    @RequestWrapper(localName = "dataClearJaxbXml", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearJaxbXml")
    @ResponseWrapper(localName = "dataClearJaxbXmlResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearJaxbXmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataClearJaxbXml(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataSaveJaxbXmlRequest", output = "http://webservice.api.common.tm/serverService/dataSaveJaxbXmlResponse")
    @RequestWrapper(localName = "dataSaveJaxbXml", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveJaxbXml")
    @ResponseWrapper(localName = "dataSaveJaxbXmlResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveJaxbXmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataSaveJaxbXml(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataSaveFasterXmlRequest", output = "http://webservice.api.common.tm/serverService/dataSaveFasterXmlResponse")
    @RequestWrapper(localName = "dataSaveFasterXml", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveFasterXml")
    @ResponseWrapper(localName = "dataSaveFasterXmlResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveFasterXmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataSaveFasterXml(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/showAboutRequest", output = "http://webservice.api.common.tm/serverService/showAboutResponse")
    @RequestWrapper(localName = "showAbout", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ShowAbout")
    @ResponseWrapper(localName = "showAboutResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ShowAboutResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.String showAbout()
;

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataClearFasterXmlRequest", output = "http://webservice.api.common.tm/serverService/dataClearFasterXmlResponse")
    @RequestWrapper(localName = "dataClearFasterXml", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearFasterXml")
    @ResponseWrapper(localName = "dataClearFasterXmlResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataClearFasterXmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataClearFasterXml(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataSaveJaxbJsonRequest", output = "http://webservice.api.common.tm/serverService/dataSaveJaxbJsonResponse")
    @RequestWrapper(localName = "dataSaveJaxbJson", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveJaxbJson")
    @ResponseWrapper(localName = "dataSaveJaxbJsonResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveJaxbJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataSaveJaxbJson(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataSaveBinaryRequest", output = "http://webservice.api.common.tm/serverService/dataSaveBinaryResponse")
    @RequestWrapper(localName = "dataSaveBinary", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveBinary")
    @ResponseWrapper(localName = "dataSaveBinaryResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataSaveBinaryResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataSaveBinary(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataLoadJaxbXmlRequest", output = "http://webservice.api.common.tm/serverService/dataLoadJaxbXmlResponse")
    @RequestWrapper(localName = "dataLoadJaxbXml", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadJaxbXml")
    @ResponseWrapper(localName = "dataLoadJaxbXmlResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadJaxbXmlResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataLoadJaxbXml(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataLoadFasterJsonRequest", output = "http://webservice.api.common.tm/serverService/dataLoadFasterJsonResponse")
    @RequestWrapper(localName = "dataLoadFasterJson", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadFasterJson")
    @ResponseWrapper(localName = "dataLoadFasterJsonResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadFasterJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataLoadFasterJson(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/serverService/dataLoadJaxbJsonRequest", output = "http://webservice.api.common.tm/serverService/dataLoadJaxbJsonResponse")
    @RequestWrapper(localName = "dataLoadJaxbJson", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadJaxbJson")
    @ResponseWrapper(localName = "dataLoadJaxbJsonResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DataLoadJaxbJsonResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-06T09:58:33.636+03:00")
    public java.lang.Boolean dataLoadJaxbJson(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );
}
