package tm.common.api.webservice;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-13T11:00:29.031+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://webservice.api.common.tm/", name = "taskService")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00", comments = "Apache CXF 3.3.2")
public interface TaskService {

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/getTasksByNameRequest", output = "http://webservice.api.common.tm/taskService/getTasksByNameResponse")
    @RequestWrapper(localName = "getTasksByName", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTasksByName")
    @ResponseWrapper(localName = "getTasksByNameResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTasksByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.util.List<tm.common.api.webservice.TaskDTO> getTasksByName(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/getTasksByNameSortedRequest", output = "http://webservice.api.common.tm/taskService/getTasksByNameSortedResponse")
    @RequestWrapper(localName = "getTasksByNameSorted", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTasksByNameSorted")
    @ResponseWrapper(localName = "getTasksByNameSortedResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTasksByNameSortedResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.util.List<tm.common.api.webservice.TaskDTO> getTasksByNameSorted(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        tm.common.api.webservice.ComparatorType arg2
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/deleteTaskRequest", output = "http://webservice.api.common.tm/taskService/deleteTaskResponse")
    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteTask")
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.lang.Boolean deleteTask(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        tm.common.api.webservice.TaskDTO arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/getTaskByIdRequest", output = "http://webservice.api.common.tm/taskService/getTaskByIdResponse")
    @RequestWrapper(localName = "getTaskById", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTaskById")
    @ResponseWrapper(localName = "getTaskByIdResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTaskByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public tm.common.api.webservice.TaskDTO getTaskById(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/deleteTasksByIdsRequest", output = "http://webservice.api.common.tm/taskService/deleteTasksByIdsResponse")
    @RequestWrapper(localName = "deleteTasksByIds", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteTasksByIds")
    @ResponseWrapper(localName = "deleteTasksByIdsResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteTasksByIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.lang.Boolean deleteTasksByIds(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/saveTaskRequest", output = "http://webservice.api.common.tm/taskService/saveTaskResponse")
    @RequestWrapper(localName = "saveTask", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.SaveTask")
    @ResponseWrapper(localName = "saveTaskResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.SaveTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.lang.Boolean saveTask(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        tm.common.api.webservice.TaskDTO arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/getAllTasksSortedRequest", output = "http://webservice.api.common.tm/taskService/getAllTasksSortedResponse")
    @RequestWrapper(localName = "getAllTasksSorted", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetAllTasksSorted")
    @ResponseWrapper(localName = "getAllTasksSortedResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetAllTasksSortedResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.util.List<tm.common.api.webservice.TaskDTO> getAllTasksSorted(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        tm.common.api.webservice.ComparatorType arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/deleteAllTasksRequest", output = "http://webservice.api.common.tm/taskService/deleteAllTasksResponse")
    @RequestWrapper(localName = "deleteAllTasks", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteAllTasks")
    @ResponseWrapper(localName = "deleteAllTasksResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.lang.Boolean deleteAllTasks(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/getTasksByProjectIdRequest", output = "http://webservice.api.common.tm/taskService/getTasksByProjectIdResponse")
    @RequestWrapper(localName = "getTasksByProjectId", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTasksByProjectId")
    @ResponseWrapper(localName = "getTasksByProjectIdResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetTasksByProjectIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.util.List<tm.common.api.webservice.TaskDTO> getTasksByProjectId(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/searchTaskRequest", output = "http://webservice.api.common.tm/taskService/searchTaskResponse")
    @RequestWrapper(localName = "searchTask", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.SearchTask")
    @ResponseWrapper(localName = "searchTaskResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.SearchTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.util.List<tm.common.api.webservice.TaskDTO> searchTask(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/deleteTasksByNameRequest", output = "http://webservice.api.common.tm/taskService/deleteTasksByNameResponse")
    @RequestWrapper(localName = "deleteTasksByName", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteTasksByName")
    @ResponseWrapper(localName = "deleteTasksByNameResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteTasksByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.lang.Boolean deleteTasksByName(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/getAllTasksRequest", output = "http://webservice.api.common.tm/taskService/getAllTasksResponse")
    @RequestWrapper(localName = "getAllTasks", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetAllTasks")
    @ResponseWrapper(localName = "getAllTasksResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetAllTasksResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public java.util.List<tm.common.api.webservice.TaskDTO> getAllTasks(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.SessionDTO arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/taskService/deleteTaskByIdRequest", output = "http://webservice.api.common.tm/taskService/deleteTaskByIdResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteTaskByIdResponse", targetNamespace = "http://webservice.api.common.tm/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-13T11:00:29.031+03:00")
    public DeleteTaskResponse deleteTaskById(

        @WebParam(partName = "parameters", name = "deleteTaskById", targetNamespace = "http://webservice.api.common.tm/")
        DeleteTask parameters
    );
}
