package tm.common.api.webservice;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T15:21:21.400+03:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://webservice.api.common.tm/", name = "userService")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00", comments = "Apache CXF 3.3.2")
public interface UserService {

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/userRegisterRequest", output = "http://webservice.api.common.tm/userService/userRegisterResponse")
    @RequestWrapper(localName = "userRegister", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UserRegister")
    @ResponseWrapper(localName = "userRegisterResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UserRegisterResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean userRegister(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/deleteUserRequest", output = "http://webservice.api.common.tm/userService/deleteUserResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://webservice.api.common.tm/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public DeleteUserByIdResponse deleteUser(

        @WebParam(partName = "parameters", name = "deleteUser", targetNamespace = "http://webservice.api.common.tm/")
        DeleteUserById parameters
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/deleteUsersByIdsRequest", output = "http://webservice.api.common.tm/userService/deleteUsersByIdsResponse")
    @RequestWrapper(localName = "deleteUsersByIds", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteUsersByIds")
    @ResponseWrapper(localName = "deleteUsersByIdsResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteUsersByIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean deleteUsersByIds(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/deleteUserByIdRequest", output = "http://webservice.api.common.tm/userService/deleteUserByIdResponse")
    @RequestWrapper(localName = "deleteUserById", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteUserById")
    @ResponseWrapper(localName = "deleteUserByIdResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean deleteUserById(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/getNewUserRequest", output = "http://webservice.api.common.tm/userService/getNewUserResponse")
    @RequestWrapper(localName = "getNewUser", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetNewUser")
    @ResponseWrapper(localName = "getNewUserResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetNewUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.util.List<tm.common.api.webservice.User> getNewUser()
;

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/userLoginRequest", output = "http://webservice.api.common.tm/userService/userLoginResponse")
    @RequestWrapper(localName = "userLogin", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UserLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UserLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public tm.common.api.webservice.Session userLogin(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/userShowProfileRequest", output = "http://webservice.api.common.tm/userService/userShowProfileResponse")
    @RequestWrapper(localName = "userShowProfile", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UserShowProfile")
    @ResponseWrapper(localName = "userShowProfileResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UserShowProfileResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.String userShowProfile(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/deleteAllUsersRequest", output = "http://webservice.api.common.tm/userService/deleteAllUsersResponse")
    @RequestWrapper(localName = "deleteAllUsers", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteAllUsers")
    @ResponseWrapper(localName = "deleteAllUsersResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean deleteAllUsers(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/getByIdRequest", output = "http://webservice.api.common.tm/userService/getByIdResponse")
    @RequestWrapper(localName = "getById", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public tm.common.api.webservice.User getById(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/updateUserRequest", output = "http://webservice.api.common.tm/userService/updateUserResponse")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.UpdateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean updateUser(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        tm.common.api.webservice.User arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/getUsersByNameRequest", output = "http://webservice.api.common.tm/userService/getUsersByNameResponse")
    @RequestWrapper(localName = "getUsersByName", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetUsersByName")
    @ResponseWrapper(localName = "getUsersByNameResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetUsersByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.util.List<tm.common.api.webservice.User> getUsersByName(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/changeUserPasswordRequest", output = "http://webservice.api.common.tm/userService/changeUserPasswordResponse")
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.ChangeUserPasswordResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean changeUserPassword(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/getAllUsersRequest", output = "http://webservice.api.common.tm/userService/getAllUsersResponse")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.GetAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.util.List<tm.common.api.webservice.User> getAllUsers(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0
    );

    @WebMethod
    @Action(input = "http://webservice.api.common.tm/userService/deleteUsersByNameRequest", output = "http://webservice.api.common.tm/userService/deleteUsersByNameResponse")
    @RequestWrapper(localName = "deleteUsersByName", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteUsersByName")
    @ResponseWrapper(localName = "deleteUsersByNameResponse", targetNamespace = "http://webservice.api.common.tm/", className = "tm.common.api.webservice.DeleteUsersByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-06-03T15:21:21.400+03:00")
    public java.lang.Boolean deleteUsersByName(

        @WebParam(name = "arg0", targetNamespace = "")
        tm.common.api.webservice.Session arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
